name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

permissions:
  contents: write # for deleting/creating a pre-release

# Manual trigger + push on test branch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
          cache: 'gradle'

      - name: Create base64 jks file
        run: echo "${{ secrets.BASE_64_SIGNING_KEY }}" > app/release_keystore.txt

      - name: Create jks file
        run: base64 -d "app/release_keystore.txt" > app/release_keystore.jks

      - name: Create Blank Local Properties File
        run: touch local.properties

      - name: Create Keystore Properties File
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Build APK Release
      - name: Build apk release project (APK)
        run: ./gradlew assemble --warning-mode all

      # Upload Artifacts
      - name: Find Release arm64
        run: echo "APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/release/ -type f -name '*arm64*.apk')" >> $GITHUB_ENV

      - name: Upload APK Release arm64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-arm64-v8a-release
          path: ${{ env.APK_PATH }}

      - name: Find Release armeabiv7
        run: echo "APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/release/ -type f -name '*armeabi*.apk')" >> $GITHUB_ENV

      - name: Upload APK Release armeabiv7
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-armeabi-v7a-release
          path: ${{ env.APK_PATH }}

      - name: Find Release universal
        run: echo "APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/release/ -type f -name '*universal*.apk')" >> $GITHUB_ENV

      - name: Upload APK Release universal
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-universal-release
          path: ${{ env.APK_PATH }}

      - name: Find Release x86
        run: echo "APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/release/ -type f -name '*x86-*.apk')" >> $GITHUB_ENV

      - name: Upload APK Release x86
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86-release
          path: ${{ env.APK_PATH }}

      - name: Find Release x86_64
        run: echo "APK_PATH=$(find ${{ env.main_project_module }}/build/outputs/apk/release/ -type f -name '*x86_64*.apk')" >> $GITHUB_ENV

      - name: Upload APK Release x86_64
        uses: actions/upload-artifact@v4
        with:
          name: ytdlnis-autogenerated-x86_64-release
          path: ${{ env.APK_PATH }}

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: YTDLnis APK release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Send Telegram Notification
      - name: Send telegram message on workflow run
        continue-on-error: true
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} triggered workflow
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
